### ISSUE TITLE
启动报错

### ISSUE THREAD

**Issue by sephrioth** [Crazysiri/chineseholiday#12]
HA为最新版本， Docker中运行， 报错如下， 实体未显示

2023-01-04 21:57:08.403 ERROR (MainThread) [homeassistant.components.sensor] chineseholiday: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 493, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 715, in async_device_update
    await task
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/util/__init__.py", line 192, in wrapper
    result = method(*args, **kwargs)
  File "/config/custom_components/chineseholiday/sensor.py", line 547, in _update
    nearest = self.nearest_holiday()
  File "/config/custom_components/chineseholiday/sensor.py", line 482, in nearest_holiday
    results = self._holiday.getHoliday()
  File "/config/custom_components/chineseholiday/holiday.py", line 387, in getHoliday
    list = self.getholidayForNMonths()
  File "/config/custom_components/chineseholiday/holiday.py", line 424, in getholidayForNMonths
    results = self.getonline40dholiday('101010100',str(y),"{:0>2d}".format(m))
  File "/config/custom_components/chineseholiday/holiday.py", line 441, in getonline40dholiday
    list = json.loads(json_str)
  File "/usr/local/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by sephrioth** [comment]
HA 更新为 2023.1 后问题消失了...

**Comment by Crazysiri** [comment]
啥情况？到底是哪个版本有问题，哪个没问题 @sephrioth

**Comment by sephrioth** [comment]
之前 HA 是 2022.12月的最后一个版本报错， 升级 HA 到 2023.01 后就一切正常了... @Crazysiri

**Comment by Crazysiri** [comment]
那就有点奇怪了，也有可能是数据解析报错吧，可能和ha没关系，不过好了就行。我还停留在2022.07，不敢乱升，怕有东西不兼容哈哈哈

**Comment by sephrioth** [comment]
是挺奇怪的， 突然就开始报错， 重启后实体都没了... 我倒是一直追着最新版本用的...

**Comment by sephrioth** [comment]
额， 我重启了下， 这个插件又启动不起来了。。。 还是一样的错误

**Comment by Crazysiri** [comment]
行，我看一下，尝试修复一下看看

**Comment by sephrioth** [comment]
> 

我感觉和 HA 没关系... 谢谢大佬

**Comment by sephrioth** [comment]
似乎是启动起来了， 没有发现报错， 我一会再多启动几次试试~

**Comment by Crazysiri** [comment]
> 似乎是启动起来了， 没有发现报错， 我一会再多启动几次试试~

看看log，有没有error日志

**Comment by sephrioth** [comment]
没有相关日志

**Comment by Crazysiri** [comment]
> 没有相关日志

嗯，那观察一下吧，就是那个三方接口可能不稳定导致的

**Comment by sephrioth** [comment]
> 

报错来了， 不过似乎实体没影响
getonline40dholiday,error:Expecting value: line 1 column 2 (char 1)
getonline40dholiday,result:Not Allowed For calendar_new

**Comment by Crazysiri** [comment]
> > 
> 
> 
> 
> 报错来了， 不过似乎实体没影响
> 
> getonline40dholiday,error:Expecting value: line 1 column 2 (char 1)
> 
> getonline40dholiday,result:Not Allowed For calendar_new

嗯因为我处理了，我想看看具体是什么。就是获取三方接口不稳定，但是没事，我是获取40天的节假日然后缓存。偶尔一次报错没事。

**Comment by sephrioth** [comment]
> > > 
> > 
> > 
> > 报错来了， 不过似乎实体没影响
> > getonline40dholiday,error:Expecting value: line 1 column 2 (char 1)
> > getonline40dholiday,result:Not Allowed For calendar_new
> 
> 嗯因为我处理了，我想看看具体是什么。就是获取三方接口不稳定，但是没事，我是获取40天的节假日然后缓存。偶尔一次报错没事。

可以可以， 那也就是说， 如果有缓存的话， 获取最新数据报错也不影响对么？ 直接使用缓存数据？

**Comment by Crazysiri** [comment]
> > > > 
> 
> > > 
> 
> > > 
> 
> > > 报错来了， 不过似乎实体没影响
> 
> > > getonline40dholiday,error:Expecting value: line 1 column 2 (char 1)
> 
> > > getonline40dholiday,result:Not Allowed For calendar_new
> 
> > 
> 
> > 嗯因为我处理了，我想看看具体是什么。就是获取三方接口不稳定，但是没事，我是获取40天的节假日然后缓存。偶尔一次报错没事。
> 
> 
> 
> 可以可以， 那也就是说， 如果有缓存的话， 获取最新数据报错也不影响对么？ 直接使用缓存数据？

对的，暂时不影响，只要一段时间有1次成功就可以，如果40天连续不成功那估计就是接口废了😂
